/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zzl_jni_JChild */

#ifndef _Included_com_example_zzl_jni_JChild
#define _Included_com_example_zzl_jni_JChild
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_jni_JChild_getNativeString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_jni_JChild_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    getString2FromC
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_jni_JChild_getString2FromC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_jni_JChild_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    accessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_example_zzl_jni_JChild_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    accessNonvirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_accessNonvirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_jni_JChild_chineseChars
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    giveArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_giveArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    getArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_zzl_jni_JChild_getArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    localRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_localRef
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    createGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_createGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    getGlobalRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_jni_JChild_getGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    deleteGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_deleteGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    exeception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_exeception
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    cached
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_cached
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_JChild
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_JChild_initIds
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
