/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zzl_jni_BsDiffPatch */

#ifndef _Included_com_example_zzl_jni_BsDiffPatch
#define _Included_com_example_zzl_jni_BsDiffPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zzl_jni_BsDiffPatch
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_BsDiffPatch_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_example_zzl_jni_BsDiffPatch_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
