/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zzl_jni_NativeThread */

#ifndef _Included_com_example_zzl_jni_NativeThread
#define _Included_com_example_zzl_jni_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zzl_jni_NativeThread
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_NativeThread_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_NativeThread
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_NativeThread_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_jni_NativeThread
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_NativeThread_nativeWorker
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_zzl_jni_NativeThread
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_zzl_jni_NativeThread_posixThreads
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
